library(shiny)
library(dplyr)
library(DT)
library(janitor)
library(readr)
library(shinycssloaders)
library(cowplot)
library(ggplot2)
library(magick)

contact_elevations<-read.csv("./contact_elevations.csv") |> tibble()
model_results<-read_csv("./model_results.csv") |> tibble()
